/* The synthetic experience and the real inference path are deliberately explicit. */
const $ = id => document.getElementById(id);
const state = {demo:true, playing:true, index:0, results:[], job:null, busy:false, image:null, imageKey:null, imagePending:null, poll:null};
function rememberJob(id){try{if(id)localStorage.setItem('rtr-job',id);else localStorage.removeItem('rtr-job');}catch{}}
const colors = {lime:'#cefa73', cyan:'#72e9d0', muted:'#87938b'};
const scene = $('sceneCanvas'), bird = $('birdCanvas'), chart = $('chartCanvas');
const time = s => `${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}`;
function setupCanvas(canvas){const r=canvas.getBoundingClientRect(), d=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(r.width*d)||canvas.height!==Math.round(r.height*d)){canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);}const ctx=canvas.getContext('2d');ctx.setTransform(d,0,0,d,0,0);return [ctx,r.width,r.height];}
function path(ctx,points,fill,stroke,lineWidth=1){if(!points.length)return;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));if(fill){ctx.closePath();ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=lineWidth;ctx.stroke();}}
function demoRow(i){const width=7.24+.23*Math.sin(i/17)+.09*Math.sin(i/5);return{timestamp_s:i*.5,width_m:width,quality:.92-.06*Math.pow(Math.sin(i/19),2),pixel_span:Math.round(682+22*Math.sin(i/17)),status:'synthetic',reasons:[],road_probability:.96,visibility:.94,sharpness:132,sensitivity_m:null};}
function current(){return state.demo?demoRow(state.index):state.results[state.index];}
function allRows(){return state.demo?Array.from({length:120},(_,i)=>demoRow(i)):state.results;}
function drawDemo(ctx,w,h,t){
  const horizon=h*.365, vanX=w*(.52+.018*Math.sin(t/22));
  const sky=ctx.createLinearGradient(0,0,0,horizon);sky.addColorStop(0,'#526e72');sky.addColorStop(.7,'#a4b4a8');sky.addColorStop(1,'#c7c9ab');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);
  const sun=ctx.createRadialGradient(w*.69,h*.15,1,w*.69,h*.15,w*.25);sun.addColorStop(0,'#e6e1b977');sun.addColorStop(1,'#e6e1b900');ctx.fillStyle=sun;ctx.fillRect(0,0,w,horizon);
  path(ctx,[[0,horizon],[0,h*.29],[w*.07,h*.25],[w*.16,h*.29],[w*.26,h*.2],[w*.36,h*.29],[w*.45,h*.3],[w*.57,h*.26],[w*.7,h*.32],[w*.9,h*.23],[w,h*.26],[w,horizon]],'#788c7f');
  path(ctx,[[0,h*.33],[w*.09,h*.3],[w*.22,h*.35],[w*.33,h*.31],[w*.45,horizon],[w*.73,horizon],[w*.82,h*.3],[w,h*.28],[w,h],[0,h]],'#57634a');
  const field=ctx.createLinearGradient(0,horizon,0,h);field.addColorStop(0,'#657255');field.addColorStop(1,'#3e4934');ctx.fillStyle=field;ctx.fillRect(0,horizon,w,h-horizon);
  // Deterministic texture is synthetic scenery, never presented as real survey footage.
  for(let i=0;i<350;i++){const y=horizon+((i*71.137+t*14)%(h-horizon)),k=(y-horizon)/(h-horizon),x=((i*137.21)%w);ctx.strokeStyle=i%3?'#a0a37925':'#192b2833';ctx.lineWidth=1+k*2;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+4+k*18,y-1-k*5);ctx.stroke();}
  const point=(u,side)=>{const bend=Math.sin(u*1.6+t*.015)*w*.022;return[vanX+bend+side*(w*.012+Math.pow(u,1.02)*w*.55),horizon+u*(h-horizon)];};
  const left=[],right=[];for(let i=0;i<=40;i++){left.push(point(i/40,-1));right.push(point(i/40,1));}
  path(ctx,[...left,...right.slice().reverse()],'#414947');
  const asphalt=ctx.createLinearGradient(0,horizon,0,h);asphalt.addColorStop(0,'#9daba520');asphalt.addColorStop(1,'#101b2030');path(ctx,[...left,...right.slice().reverse()],asphalt);
  for(let i=0;i<180;i++){const u=((i*.0713+t*.04)%1),p=point(u,(Math.sin(i*2.33))*.92);ctx.fillStyle='#c2d1c315';ctx.fillRect(p[0],p[1],1+u*3,.7+u);}
  for(const side of [-1,1]){path(ctx,Array.from({length:41},(_,i)=>point(i/40,side*.95)),null,'#deddb7',1.4);path(ctx,Array.from({length:41},(_,i)=>{const p=point(i/40,side*1.09);return[p[0],p[1]-2-i*.15];}),null,'#aeb7a7',1.5);}
  for(let j=0;j<13;j++){const u=((j/13+t*.02)%1),u2=Math.min(1,u+.016+u*.035),l1=point(u,-.007),r1=point(u,.007),l2=point(u2,-.007),r2=point(u2,.007);path(ctx,[l1,r1,r2,l2],'#f0e9b0bb');}
  for(let j=0;j<14;j++){const u=(j/14+t*.013)%1;for(const side of[-1,1]){const p=point(u,side*1.13);ctx.strokeStyle='#c4c8ac';ctx.lineWidth=1+u*3;ctx.beginPath();ctx.moveTo(p[0],p[1]);ctx.lineTo(p[0],p[1]-4-u*28);ctx.stroke();}}
  // Small distant vehicle and roadside vegetation establish depth in the demo.
  const car=point(.16,.4);ctx.fillStyle='#283337';ctx.fillRect(car[0]-w*.009,car[1]-h*.025,w*.023,h*.025);ctx.fillStyle='#96a6a0';ctx.fillRect(car[0]-w*.006,car[1]-h*.023,w*.016,h*.008);
  for(let j=0;j<20;j++){let x=(j*91.37)%w,y=horizon-5-(j%4)*6;if(Math.abs(x-vanX)<w*.13)continue;ctx.fillStyle=j%2?'#344f44':'#3c5546';ctx.beginPath();ctx.ellipse(x,y,8+(j%5)*3,12+(j%4)*5,0,0,Math.PI*2);ctx.fill();}
  if($('overlayToggle').checked){path(ctx,[...left,...right.slice().reverse()],'#4ee5b02f');ctx.save();path(ctx,[...left,...right.slice().reverse()],'#0000');ctx.clip();for(let i=1;i<12;i++){const u=(i/12)**1.5;path(ctx,[point(u,-1),point(u,1)],null,'#a7f1b03f',.8);}for(let i=-5;i<=5;i++){path(ctx,Array.from({length:41},(_,j)=>point(j/40,i/5)),null,'#b3f6b32a',.8);}ctx.restore();}
  if($('lineToggle').checked){path(ctx,left,null,colors.cyan,2);path(ctx,right,null,colors.lime,2);const u=.70,p1=point(u,-1),p2=point(u,1);path(ctx,[p1,p2],null,colors.lime,1.5);for(const p of[p1,p2]){ctx.fillStyle=colors.lime;ctx.beginPath();ctx.arc(p[0],p[1],3,0,Math.PI*2);ctx.fill();path(ctx,[[p[0],p[1]-7],[p[0],p[1]+7]],null,colors.lime,1.5);}}
  const vignette=ctx.createRadialGradient(w*.5,h*.5,w*.15,w*.5,h*.5,w*.66);vignette.addColorStop(0,'#0000');vignette.addColorStop(1,'#08131066');ctx.fillStyle=vignette;ctx.fillRect(0,0,w,h);
}
function drawReal(ctx,w,h,row){ctx.fillStyle='#101918';ctx.fillRect(0,0,w,h);if(!row){ctx.fillStyle=colors.muted;ctx.textAlign='center';ctx.font='12px sans-serif';ctx.fillText(state.busy?'Waiting for the first analyzed frame…':'No analyzed frames yet',w/2,h/2);return;}
  if(state.imageKey!==row.image&&state.imagePending!==row.image){const im=new Image();state.imagePending=row.image;im.onload=()=>{if(!state.demo&&current()?.image===row.image){state.image=im;state.imageKey=row.image;}if(state.imagePending===row.image)state.imagePending=null;};im.onerror=()=>{if(state.imagePending===row.image)state.imagePending=null;};im.src=row.image;}
  if(!state.image||state.imageKey!==row.image){ctx.fillStyle=colors.muted;ctx.textAlign='center';ctx.font='12px sans-serif';ctx.fillText('Loading frame…',w/2,h/2);return;}
  const scale=Math.min(w/row.image_width,h/row.image_height),ox=(w-row.image_width*scale)/2,oy=(h-row.image_height*scale)/2;
  ctx.save();ctx.translate(ox,oy);ctx.scale(scale,scale);ctx.drawImage(state.image,0,0,row.image_width,row.image_height);
  if($('overlayToggle').checked){ctx.beginPath();for(const ring of(row.mask_rings||[row.polygon||[]])){ring.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();}ctx.fillStyle='#4ce5a735';ctx.fill('evenodd');}
  if($('lineToggle').checked){path(ctx,[...(row.polygon||[]),(row.polygon||[])[0]].filter(Boolean),null,colors.cyan,2/scale);const pairs=row.sections?.length?row.sections.map(s=>s.pixels):row.pixel_pairs||[];pairs.forEach((pair,i)=>{if(i%3!==0)return;path(ctx,pair,null,colors.lime,1/scale);for(const p of pair){ctx.fillStyle=colors.lime;ctx.beginPath();ctx.arc(...p,2.5/scale,0,Math.PI*2);ctx.fill();}});}
  ctx.restore();
}
function drawBird(){const[ctx,w,h]=setupCanvas(bird);ctx.clearRect(0,0,w,h);ctx.strokeStyle='#303b32';ctx.lineWidth=.6;for(let x=0;x<w;x+=20){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}for(let y=0;y<h;y+=20){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}
  const row=current();if(!state.demo&&!row?.sections?.length){ctx.fillStyle='#91a18e';ctx.textAlign='center';ctx.font='11px sans-serif';ctx.fillText('Ground plane unavailable',w/2,h*.45);ctx.font='9px sans-serif';ctx.fillStyle='#67766a';ctx.fillText('Camera calibration required',w/2,h*.45+18);return;}
  let left=[],right=[];if(state.demo){for(let j=0;j<25;j++){const y=j/24,x=w*.5+Math.sin(y*2+state.index/30)*w*.065;left.push([x-w*.18,y*h]);right.push([x+w*.18,y*h]);}}else{const secs=[...row.sections].sort((a,b)=>a.distance_m-b.distance_m),maxZ=Math.max(...secs.flatMap(s=>s.ground.map(p=>p[1]))),minZ=Math.min(...secs.flatMap(s=>s.ground.map(p=>p[1]))),maxX=Math.max(6,...secs.flatMap(s=>s.ground.map(p=>Math.abs(p[0]))));const tr=p=>[w*.5+p[0]/maxX*w*.42,h-10-(p[1]-minZ)/(maxZ-minZ||1)*(h-20)];left=secs.map(s=>tr(s.ground[0]));right=secs.map(s=>tr(s.ground[1]));}
  path(ctx,[...left,...right.slice().reverse()],'#b4f58716');path(ctx,left,null,colors.cyan,1.5);path(ctx,right,null,colors.lime,1.5);ctx.setLineDash([4,5]);path(ctx,left.map((p,i)=>[(p[0]+right[i][0])/2,(p[1]+right[i][1])/2]),null,'#d0e7b457');ctx.setLineDash([]);for(let i=2;i<left.length;i+=4)path(ctx,[left[i],right[i]],null,'#b9ed8680',1);ctx.fillStyle=colors.lime;ctx.textAlign='center';ctx.font='10px monospace';ctx.fillText(`${row.width_m.toFixed(2)} m`,w*.5,h*.60);}
function drawChart(){const[ctx,w,h]=setupCanvas(chart);ctx.clearRect(0,0,w,h);const rows=allRows(),metric=state.demo||rows.some(r=>r.width_m!=null),values=rows.map(r=>metric?r.width_m:r.pixel_span),valid=values.filter(v=>v!=null&&Number.isFinite(v));const lo=valid.length?Math.min(...valid):0,hi=valid.length?Math.max(...valid):1,pad=Math.max((hi-lo)*.3,metric?.15:10),min=lo-pad,max=hi+pad,left=35,right=w-8,top=7,bottom=h-20;
  ctx.font='8px monospace';ctx.textAlign='right';for(let i=0;i<3;i++){const y=top+i*(bottom-top)/2;ctx.strokeStyle='#313a34';ctx.lineWidth=.6;path(ctx,[[left,y],[right,y]],null,'#313a34',.6);ctx.fillStyle=colors.muted;ctx.fillText((max-i*(max-min)/2).toFixed(metric?1:0),left-8,y+3);}
  if(!valid.length){ctx.textAlign='center';ctx.fillStyle=colors.muted;ctx.fillText('Measurements appear after inference',w/2,h/2);return;}
  const pt=(v,i)=>[left+i/Math.max(1,rows.length-1)*(right-left),bottom-(v-min)/(max-min)*(bottom-top)];let run=[];function strokeRun(){if(run.length){path(ctx,[[run[0][0],bottom],...run,[run.at(-1)[0],bottom]],'#a1db6a10');path(ctx,run,null,colors.lime,1.5);}run=[];}
  values.forEach((v,i)=>{if(v==null){strokeRun();return;}run.push(pt(v,i));});strokeRun();const x=left+state.index/Math.max(1,rows.length-1)*(right-left);path(ctx,[[x,top],[x,bottom]],null,'#d8edcb70',1);if(values[state.index]!=null){const p=pt(values[state.index],state.index);ctx.fillStyle=colors.lime;ctx.beginPath();ctx.arc(...p,3,0,Math.PI*2);ctx.fill();}
  ctx.fillStyle=colors.muted;ctx.textAlign='left';ctx.fillText('00:00',left,h-3);ctx.textAlign='right';ctx.fillText(time(rows.at(-1)?.timestamp_s||0),right,h-3);
}
function evidence(items){$('evidenceRows').replaceChildren(...items.map(([label,value])=>{const div=document.createElement('div');div.className='evidence-row';const l=document.createElement('span'),b=document.createElement('b');l.textContent=label;b.textContent=value;div.append(l,b);return div;}));}
function refresh(){const row=current(),rows=allRows();$('timeline').max=Math.max(0,rows.length-1);$('timeline').value=state.index;$('timeline').disabled=!rows.length;$('playButton').textContent=state.playing?'Ⅱ':'▶';$('timeLabel').textContent=time(row?.timestamp_s||0);$('durationLabel').textContent=time(rows.at(-1)?.timestamp_s||0);$('frameLabel').textContent=`FRAME ${String((row?.frame_index??state.index)+1).padStart(4,'0')}`;
  const metric=row?.width_m!=null;$('mainMetric').classList.toggle('unscaled',!metric);$('mainMetric').innerHTML=metric?`${row.width_m.toFixed(2)}<span>m</span>`:(state.job?.calibration?'Needs review':'Scale required');
  $('metricNote').textContent=state.demo?'Synthetic measurement':metric?(row.sensitivity_m?`Sensitivity ${row.sensitivity_m[0].toFixed(2)}–${row.sensitivity_m[1].toFixed(2)} m`:'Conditional ground-plane estimate'):'No defensible metre estimate';
  $('qualityTitle').textContent=state.demo?'Illustrative quality':'Image / geometry quality';$('qualityValue').textContent=row?`${Math.round(row.quality*100)} / 100`:'—';$('qualityBar').style.width=`${(row?.quality||0)*100}%`;$('qualityCaveat').textContent=state.demo?'Demo score only. Real quality scores are heuristic, not an accuracy guarantee.':'Heuristic diagnostic. Not a probability of accuracy or a validated confidence interval.';
  $('pixelSpan').innerHTML=row?.pixel_span!=null?`${row.pixel_span} <em>px</em>`:'—';$('scaleSource').textContent=state.demo?'Synthetic':state.job?.calibration?'Camera profile':'Unavailable';$('birdBadge').textContent=state.demo?'SYNTHETIC':metric?'PLANAR':'NO SCALE';$('birdLegend').textContent=state.demo?'Illustrative ground plane':metric?'Conditional ground plane':'No metric reconstruction';
  $('sceneLabel').innerHTML=`<span class="live-dot"></span> ${state.demo?'SYNTHETIC SCENE':'SEGFORMER / ROAD MASK'}`;$('sceneScore').textContent=state.demo?'ILLUSTRATIVE':row?.road_probability!=null?`${Math.round(row.road_probability*100)}% MEAN SOFTMAX`:'WAITING';$('measurementTag').hidden=!state.demo&&!row;$('measurementTag').querySelector('strong').innerHTML=metric?`${row.width_m.toFixed(2)} <em>m</em>`:row?.pixel_span!=null?`${row.pixel_span} <em>px</em>`:'No span';$('measurementTag').querySelector('small').textContent=metric?'PROJECTED CARRIAGEWAY':'VISIBLE IMAGE SPAN';$('measurementTag').querySelector('span').textContent=state.demo?'Synthetic example · known geometry':metric?'Conditional on calibration + flat road':'Unscaled · not a physical width';
  $('resolutionLabel').textContent=state.demo?'DEMO VIEW':row?`${row.image_width} × ${row.image_height}`:'—';$('playbackLabel').textContent=state.demo?'DEMO LOOP':'SAMPLED FRAMES';$('viewerCaption').textContent=state.demo?'A preview of the measurement experience. All demo geometry and readings are simulated.':'Analyzed frames from your video. Lines indicate visible cross-sections; masks can be wrong.';$('engineLabel').textContent=state.demo?'DEMO ENGINE':'SEGFORMER B0';
  const metricChart=state.demo||rows.some(r=>r.width_m!=null);$('chartTitle').innerHTML=`${metricChart?'WIDTH':'PIXEL SPAN'} PROFILE <small>/ ${state.demo?'synthetic metres':metricChart?'conditional metres':'preview pixels, not metres'}</small>`;$('chartLegend').innerHTML=`<i class="legend-line"></i> ${state.demo?'Synthetic width':metricChart?'Accepted metric estimates':'Visible image span'}`;$('chartSummary').textContent=state.demo?'60 s preview':`${rows.length} sampled frames`;$('evidenceBadge').textContent=state.demo?'DEMO':row?.status?.toUpperCase()||'WAITING';
  evidence(state.demo?[['Road segmentation','Simulated'],['Boundary visibility','Simulated'],['Metric reference','Known synthetic geometry']]:[['Mean road softmax',row?.road_probability!=null?`${Math.round(row.road_probability*100)}% (uncalibrated)`:'—'],['Boundary visibility',row?.visibility!=null?`${Math.round(row.visibility*100)} / 100`:'—'],['Metric reference',state.job?.calibration?'User camera calibration':'Missing']]);$('reviewNote').textContent=state.demo?'A trustworthy measurement starts with a known scale.':row?.reasons?.length?row.reasons.join(' · '):metric?'Assumes a locally flat road and unchanged camera pose.':'Awaiting segmentation evidence.';drawBird();drawChart();
}
function resetDemo(){if(state.busy)return;clearTimeout(state.poll);rememberJob(null);history.replaceState(null,'',location.pathname);state.demo=true;state.index=0;state.playing=true;state.results=[];state.job=null;state.image=null;state.imageKey=null;$('surveyName').textContent='The coastal approach';$('surveySubtitle').textContent='INTERACTIVE SYNTHETIC DEMO · NO ML INFERENCE';$('modeBadge').textContent='DEMO / ILLUSTRATIVE';$('statusTitle').textContent='Explore the demo, then bring your own road.';$('statusDetail').textContent='MP4, MOV, AVI, MKV, WebM · up to 500 MB / 10 min';$('progressWrap').hidden=true;$('cancelButton').hidden=true;refresh();}
function setBusy(value){state.busy=value;$('uploadButton').disabled=value;$('demoButton').disabled=value;$('analyzeButton').disabled=value;$('cancelButton').hidden=!value;}
$('playButton').onclick=()=>{state.playing=!state.playing;refresh();};$('timeline').oninput=e=>{state.index=Number(e.target.value);state.playing=false;refresh();};$('demoButton').onclick=resetDemo;
chart.onclick=e=>{const r=chart.getBoundingClientRect();state.index=Math.round(Math.max(0,Math.min(1,(e.clientX-r.left-35)/(r.width-43)))*Math.max(0,allRows().length-1));state.playing=false;refresh();};
$('fullscreenButton').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('scene').requestFullscreen();}catch(e){$('statusTitle').textContent='Fullscreen is unavailable in this browser.';}};
document.querySelectorAll('.close-dialog').forEach(button=>button.onclick=()=>button.closest('dialog').close());
$('uploadButton').onclick=()=>$('uploadDialog').showModal();$('calibrationNav').onclick=()=>{if(state.busy)return;$('uploadDialog').showModal();$('calibrationDetails').open=true;};$('infoButton').onclick=$('infoNav').onclick=()=>$('infoDialog').showModal();
$('videoInput').onchange=()=>{$('fileLabel').textContent=$('videoInput').files[0]?.name||'Choose a dashcam video';$('uploadError').textContent='';};
$('uploadForm').onsubmit=async event=>{event.preventDefault();if(state.busy)return;const file=$('videoInput').files[0];if(!file)return;const error=$('uploadError');error.textContent='';if(file.size>500*1024*1024){error.textContent='This clip exceeds 500 MB. Split or compress it first.';return;}const calibration=$('calibrationInput').value.trim();if(calibration){try{const obj=JSON.parse(calibration);for(const k of['image_width','image_height','fx','fy','cx','cy','height_m','pitch_deg'])if(typeof obj[k]!=='number'||!Number.isFinite(obj[k]))throw Error(`Missing or invalid ${k}`);}catch(e){error.textContent=`Calibration JSON: ${e.message}`;return;}}
  const form=new FormData();form.append('video',file);form.append('calibration',calibration);form.append('sample_hz',$('sampleRate').value);setBusy(true);$('analyzeButton').textContent='Uploading…';
  try{const response=await fetch('/api/jobs',{method:'POST',body:form});const data=await response.json();if(!response.ok)throw Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));state.demo=false;state.index=0;state.results=[];state.playing=false;state.job={id:data.id,calibration:calibration?JSON.parse(calibration):null};state.image=null;state.imageKey=null;$('surveyName').textContent=file.name;$('surveySubtitle').textContent='LOCAL VIDEO ANALYSIS · SEGFORMER B0';$('modeBadge').textContent=calibration?'CALIBRATED / CONDITIONAL':'VIDEO ONLY / NO METRIC SCALE';$('statusTitle').textContent='Preparing inference…';$('statusDetail').textContent='First run downloads model weights.';$('progressWrap').hidden=false;$('progressBar').style.width='0%';$('uploadDialog').close();refresh();pollJob(data.id);}catch(e){error.textContent=e.message;setBusy(false);}finally{$('analyzeButton').innerHTML='Analyze survey <span>↗</span>';}
};
async function pollJob(id){try{const response=await fetch(`/api/jobs/${id}`);if(response.status===404){rememberJob(null);setBusy(false);$('statusTitle').textContent='This survey session is no longer available. Start a new survey.';$('statusDetail').textContent='Saved results remain in the local data folder.';return;}if(!response.ok)throw Error('Cannot read survey status');const job=await response.json();if(state.job?.id!==id)return;rememberJob(id);history.replaceState(null,'',`?survey=${id}`);state.job=job;state.results=job.results||[];state.index=Math.min(state.index,Math.max(0,state.results.length-1));$('surveyName').textContent=job.filename;$('surveySubtitle').textContent='LOCAL VIDEO ANALYSIS · SEGFORMER B0';$('modeBadge').textContent=job.calibration?'CALIBRATED / CONDITIONAL':'VIDEO ONLY / NO METRIC SCALE';$('statusTitle').textContent=job.message||job.status;$('statusDetail').textContent=`${state.results.length} frames · ${Math.round((job.progress||0)*100)}%${job.truncated?' · partial clip coverage':''}`;$('progressBar').style.width=`${(job.progress||0)*100}%`;refresh();if(['complete','failed','cancelled'].includes(job.status)){setBusy(false);if(job.status==='failed')$('reviewNote').textContent=`Analysis failed: ${job.message}`;return;}state.poll=setTimeout(()=>pollJob(id),1600);}catch(e){$('statusTitle').textContent=`Connection interrupted: ${e.message}`;$('statusDetail').textContent='Retrying in 5 seconds…';state.poll=setTimeout(()=>pollJob(id),5000);}}
$('cancelButton').onclick=async()=>{if(!state.job)return;try{const res=await fetch(`/api/jobs/${state.job.id}/cancel`,{method:'POST'});if(!res.ok)throw Error('Cancel request failed');$('statusTitle').textContent='Stopping after the current inference frame…';}catch(e){$('statusTitle').textContent=e.message;}};
$('exportButton').onclick=()=>{$('exportNote').textContent=state.demo?'Synthetic demo export. These values are illustrative and are not measurements of a real road.':'Export sampled observations, quality reasons and calibration provenance. Missing widths remain empty.';$('exportDialog').showModal();};
function download(format){if(!state.demo){if(!state.job||!state.results.length){$('exportNote').textContent='There are no analyzed frames to export yet.';return;}const a=document.createElement('a');a.href=`/api/jobs/${state.job.id}/export?format=${format}`;a.download='';a.click();return;}const rows=allRows().map(r=>({source:'synthetic_demo',timestamp_s:r.timestamp_s,illustrative_width_m:Number(r.width_m.toFixed(3)),illustrative_quality:r.quality}));const data=format==='json'?JSON.stringify({synthetic:true,notice:'Not real survey measurements',results:rows},null,2):'source,timestamp_s,illustrative_width_m,illustrative_quality\n'+rows.map(r=>Object.values(r).join(',')).join('\n');const url=URL.createObjectURL(new Blob([data],{type:format==='json'?'application/json':'text/csv'}));const a=document.createElement('a');a.href=url;a.download=`synthetic-road-demo.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('jsonExport').onclick=()=>download('json');$('csvExport').onclick=()=>download('csv');
let lastStep=0;function animate(now){const[ctx,w,h]=setupCanvas(scene);if(state.demo)drawDemo(ctx,w,h,state.index*.5);else drawReal(ctx,w,h,current());if(state.playing&&now-lastStep>500){state.index=(state.index+1)%Math.max(1,allRows().length);lastStep=now;refresh();}requestAnimationFrame(animate);}new ResizeObserver(()=>{drawBird();drawChart();}).observe(document.querySelector('.workspace'));
fetch('/api/health').then(r=>{if(!r.ok)throw Error();return r.json();}).then(()=>{$('connection').textContent='Local inference engine';}).catch(()=>{$('connection').textContent='Demo only · API offline';});
let savedJob=new URLSearchParams(location.search).get('survey');try{savedJob=savedJob||localStorage.getItem('rtr-job');}catch{}
if(savedJob&&/^[a-f0-9]{32}$/.test(savedJob)){state.demo=false;state.playing=false;state.job={id:savedJob};setBusy(true);$('progressWrap').hidden=false;refresh();pollJob(savedJob);}else resetDemo();requestAnimationFrame(animate);
