const $=id=>document.getElementById(id);
const colors={lime:'#cefa73',cyan:'#72e9d0',muted:'#87938b'};
const state={demo:true,playing:true,index:0,results:[],job:null,busy:false,image:null,imageKey:null,pendingImage:null,poll:null,map:null,mapKey:null,videoKey:null,mapZoom:1,mapPan:[0,0],time:0};
const scene=$('sceneCanvas'),bird=$('birdCanvas'),chart=$('chartCanvas'),mapCanvas=$('mapCanvas'),video=$('surveyVideo');
const time=s=>`${String(Math.floor(Math.max(0,s)/60)).padStart(2,'0')}:${String(Math.floor(Math.max(0,s)%60)).padStart(2,'0')}`;
function setupCanvas(canvas){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(r.width*d)||canvas.height!==Math.round(r.height*d)){canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);}const ctx=canvas.getContext('2d');ctx.setTransform(d,0,0,d,0,0);return[ctx,r.width,r.height];}
function path(ctx,points,fill,stroke,lineWidth=1){if(!points?.length)return;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));if(fill){ctx.closePath();ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=lineWidth;ctx.stroke();}}
function remembered(id){try{if(id)localStorage.setItem('rtr-job',id);else localStorage.removeItem('rtr-job');}catch{}}
function demoRow(i){return{timestamp_s:i*.5,width_m:7.24+.23*Math.sin(i/17)+.09*Math.sin(i/5),quality:.92-.06*Math.sin(i/19)**2,status:'synthetic',reasons:[],road_probability:.96,visibility:.94};}
function rows(){return state.demo?Array.from({length:120},(_,i)=>demoRow(i)):state.results;}
function current(){return state.demo?demoRow(state.index):state.results[state.index];}
function widthOf(row){return row?.width_m??row?.rough_width_m??null;}
function sectionsOf(row){return row?.sections?.length?row.sections:row?.rough_sections||[];}
function clipDuration(){return state.demo?60:state.job?.duration_s||state.results.at(-1)?.timestamp_s||0;}
function indexAt(t){const list=state.results;if(!list.length)return 0;let a=0,b=list.length-1;while(a<b){const m=Math.ceil((a+b)/2);if(list[m].timestamp_s<=t)a=m;else b=m-1;}return a;}
function videoMode(){return !state.demo&&$('viewMode').value==='video'&&Boolean(state.job?.annotated_url);}
function setBusy(busy){state.busy=busy;$('uploadButton').disabled=busy;$('reprocessButton').disabled=busy;$('demoButton').disabled=busy;$('analyzeButton').disabled=busy;$('cancelButton').hidden=!busy;}
function loadVideo(){const enabled=videoMode();video.hidden=!enabled;scene.hidden=enabled;$('lineToggle').disabled=enabled;$('lineToggle').title=enabled?'Measurement lines are included in the annotated video; inspect frames for separate controls.':'';$('measurementTag').hidden=enabled||(!state.demo&&!current());$('.not-existing');
  if(!enabled){video.pause();return;}
  const url=$('overlayToggle').checked?state.job.annotated_url:state.job.source_url;
  if(state.videoKey!==url){const at=state.time,playing=state.playing;state.videoKey=url;video.src=url;video.onloadedmetadata=()=>{video.currentTime=Math.min(at,Math.max(0,video.duration-.01));video.playbackRate=Number($('playbackSpeed').value);if(playing)video.play().catch(()=>{state.playing=false;});};video.load();}
}
function drawReal(ctx,w,h,row){ctx.fillStyle='#0c1410';ctx.fillRect(0,0,w,h);if(!row){ctx.fillStyle=colors.muted;ctx.textAlign='center';ctx.font='12px sans-serif';ctx.fillText(state.busy?'Preparing the first analyzed frame…':'No analyzed frames',w/2,h/2);return;}
  if(state.imageKey!==row.image&&state.pendingImage!==row.image){const im=new Image();state.pendingImage=row.image;im.onload=()=>{if(!state.demo&&current()?.image===row.image){state.image=im;state.imageKey=row.image;}if(state.pendingImage===row.image)state.pendingImage=null;};im.onerror=()=>{if(state.pendingImage===row.image)state.pendingImage=null;};im.src=row.image;}
  if(!state.image||state.imageKey!==row.image)return;
  const scale=Math.min(w/row.image_width,h/row.image_height),ox=(w-row.image_width*scale)/2,oy=(h-row.image_height*scale)/2;
  ctx.save();ctx.translate(ox,oy);ctx.scale(scale,scale);ctx.drawImage(state.image,0,0,row.image_width,row.image_height);
  if($('overlayToggle').checked){ctx.beginPath();for(const ring of row.mask_rings||[row.polygon||[]]){ring.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();}ctx.fillStyle='#54e7a63f';ctx.fill('evenodd');}
  if($('lineToggle').checked){path(ctx,[...(row.polygon||[]),(row.polygon||[])[0]].filter(Boolean),null,colors.cyan,1.5/scale);const pairs=sectionsOf(row).length?sectionsOf(row).map(s=>s.pixels):row.pixel_pairs||[];pairs.forEach((pair,i)=>{if(i%Math.max(1,Math.floor(pairs.length/5)))return;path(ctx,pair,null,colors.lime,1/scale);});}ctx.restore();
}
function drawBird(){const[ctx,w,h]=setupCanvas(bird);ctx.clearRect(0,0,w,h);for(let x=0;x<w;x+=20)path(ctx,[[x,0],[x,h]],null,'#303b32',.6);for(let y=0;y<h;y+=20)path(ctx,[[0,y],[w,y]],null,'#303b32',.6);
  const row=current();let left=[],right=[];if(state.demo){for(let j=0;j<25;j++){const y=j/24,x=w*.5+Math.sin(y*2+state.index/30)*w*.065;left.push([x-w*.18,y*h]);right.push([x+w*.18,y*h]);}}else{const sections=sectionsOf(row);if(!sections.length){ctx.textAlign='center';ctx.font='10px sans-serif';ctx.fillStyle=colors.muted;ctx.fillText('Insufficient geometry in this frame',w/2,h/2);return;}const sorted=[...sections].sort((a,b)=>a.distance_m-b.distance_m),xs=sorted.flatMap(s=>s.ground.map(p=>Math.abs(p[0]))),zs=sorted.flatMap(s=>s.ground.map(p=>p[1])),maxX=Math.max(3,...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs),tr=p=>[w/2+p[0]/maxX*w*.42,h-10-(p[1]-minZ)/(maxZ-minZ||1)*(h-20)];left=sorted.map(s=>tr(s.ground[0]));right=sorted.map(s=>tr(s.ground[1]));}
  path(ctx,[...left,...right.slice().reverse()],'#b4f58720');path(ctx,left,null,colors.cyan,1.5);path(ctx,right,null,colors.lime,1.5);for(let i=1;i<left.length;i+=3)path(ctx,[left[i],right[i]],null,'#d0ed8855',.8);ctx.fillStyle=colors.lime;ctx.font='11px monospace';ctx.textAlign='center';const width=widthOf(row);if(width!=null)ctx.fillText(`${state.demo||row.width_m!=null?'':'~'}${width.toFixed(1)} m`,w/2,h*.6);
}
function drawChart(){const[ctx,w,h]=setupCanvas(chart);ctx.clearRect(0,0,w,h);const list=rows(),values=list.map(widthOf),valid=values.filter(v=>v!=null),lo=valid.length?Math.min(...valid):0,hi=valid.length?Math.max(...valid):10,pad=Math.max(.5,(hi-lo)*.3),min=Math.max(0,lo-pad),max=hi+pad,left=34,right=w-8,top=7,bottom=h-20,duration=clipDuration();
  ctx.font='8px monospace';ctx.textAlign='right';for(let i=0;i<3;i++){const y=top+i*(bottom-top)/2;path(ctx,[[left,y],[right,y]],null,'#303c33',.6);ctx.fillStyle=colors.muted;ctx.fillText((max-i*(max-min)/2).toFixed(1),left-7,y+3);}
  if(!valid.length){ctx.textAlign='center';ctx.fillStyle=colors.muted;ctx.fillText('Metre estimates appear after analysis',w/2,h/2);return;}
  const point=(v,i)=>[left+list[i].timestamp_s/Math.max(.01,duration)*(right-left),bottom-(v-min)/(max-min)*(bottom-top)];let run=[];
  function flush(){if(run.length){path(ctx,[[run[0][0],bottom],...run,[run.at(-1)[0],bottom]],'#c4f47612');path(ctx,run,null,colors.lime,1.5);}run=[];}
  values.forEach((v,i)=>{if(v==null)flush();else run.push(point(v,i));});flush();const x=left+state.time/Math.max(.01,duration)*(right-left);path(ctx,[[x,top],[x,bottom]],null,'#e2efd2aa',1);ctx.fillStyle=colors.muted;ctx.textAlign='left';ctx.fillText('00:00',left,h-3);ctx.textAlign='right';ctx.fillText(time(duration),right,h-3);
}
function evidence(items){$('evidenceRows').replaceChildren(...items.map(([label,value])=>{const div=document.createElement('div');div.className='evidence-row';const l=document.createElement('span'),r=document.createElement('b');l.textContent=label;r.textContent=value;div.append(l,r);return div;}));}
function refresh(){const row=current(),width=widthOf(row),rough=!state.demo&&row?.width_m==null&&row?.rough_width_m!=null;
  $('timeline').max=Math.max(.01,clipDuration());$('timeline').value=state.time;$('timeLabel').textContent=time(state.time);$('durationLabel').textContent=time(clipDuration());$('playButton').textContent=state.playing?'Ⅱ':'▶';$('frameLabel').textContent=`${videoMode()?'VIDEO':'FRAME'} ${String((row?.frame_index??state.index)+1).padStart(4,'0')}`;
  $('metricTitle').textContent=rough?'ROUGH ROAD WIDTH':state.demo?'SYNTHETIC ROAD WIDTH':'CALIBRATED ROAD WIDTH';$('mainMetric').classList.toggle('unscaled',width==null);$('mainMetric').innerHTML=width!=null?`${rough?'~':''}${width.toFixed(rough?1:2)}<span>m</span>`:'Needs review';
  $('metricNote').textContent=state.demo?'Synthetic example':rough?`${row.rough_range_m?.[0]}–${row.rough_range_m?.[1]} m scenario range${row.estimate_kind==='visible_lower_bound'?' · visible surface only':''}`:row?.width_m!=null?`Conditional plane estimate${row.sensitivity_m?' · '+row.sensitivity_m.join('–')+' m sensitivity':''}`:'Not enough reliable geometry in this frame';
  $('qualityValue').textContent=row?`${Math.round(row.quality*100)} / 100`:'—';$('qualityBar').style.width=`${(row?.quality||0)*100}%`;$('qualityCaveat').textContent=state.demo?'Synthetic demo values. Not measurements of real footage.':rough?'Rough scale depends on depth, camera FOV and height assumptions. The range is not a confidence interval.':'Heuristic evidence score, not a probability of width accuracy.';
  $('scaleSource').textContent=state.demo?'Synthetic':row?.width_m!=null?'Calibration':row?.depth_anchor?.applied?'Depth + height prior':rough?'Learned depth':'Unavailable';$('maskSource').textContent=state.demo?'Synthetic':row?.inference==='flow_tracked'?'Flow tracked':row?'B2 keyframe':'Waiting';
  $('birdBadge').textContent=state.demo?'SYNTHETIC':rough?'APPROXIMATE':row?.width_m!=null?'CALIBRATED':'NO GEOMETRY';$('birdLegend').textContent=state.demo?'Illustrative ground plane':rough?'Approximate camera-space section':'Local cross-sections';
  $('sceneLabel').textContent=state.demo?'SYNTHETIC SCENE':videoMode()?($('overlayToggle').checked?'MASKED VIDEO / ALL OUTPUT FRAMES':'ORIGINAL VIDEO'):row?.inference==='flow_tracked'?'OPTICAL-FLOW TRACKED MASK':'SEGFORMER B2 / ROAD';$('sceneScore').textContent=state.demo?'ILLUSTRATIVE':row?.road_probability!=null?`${Math.round(row.road_probability*100)}% ROAD SOFTMAX`:'WAITING';
  $('measurementTag').hidden=videoMode()||(!state.demo&&!row);$('measurementTag').querySelector('strong').innerHTML=width!=null?`${rough?'~':''}${width.toFixed(1)} <em>m</em>`:'No estimate';$('measurementTag').querySelector('small').textContent=rough?'ROUGH WIDTH ESTIMATE':'CARRIAGEWAY WIDTH';$('measurementTag').querySelector('span').textContent=state.demo?'Synthetic example':rough?`${row.rough_range_m.join('–')} m · ${row.estimate_kind==='visible_lower_bound'?'visible surface only':'assumption-dependent'}`:'Conditional on calibration';
  $('resolutionLabel').textContent=state.demo?'DEMO VIEW':row?`${row.image_width} × ${row.image_height}`:'—';$('engineLabel').textContent=state.demo?'DEMO ENGINE':'B2 + DEPTH V2';$('viewerCaption').textContent=state.demo?'Synthetic experience preview. Upload footage for real inference.':videoMode()?'Full video with tracked masks between model keyframes. Width labels remain approximate.':`${state.results.length} inspection snapshots. Full masked video becomes available after processing.`;
  $('chartTitle').innerHTML='WIDTH PROFILE <small>/ '+(state.demo?'synthetic metres':'calibrated or approximate metres')+'</small>';$('chartSummary').textContent=state.demo?'60 s preview':`${state.results.length} snapshots · ${state.job?.processed_video_frames||0} video frames`;$('chartLegend').innerHTML='<i class="legend-line"></i> '+(state.demo?'Synthetic width':'Width estimate; gaps indicate no estimate');$('evidenceBadge').textContent=state.demo?'DEMO':(row?.status||'WAITING').toUpperCase().replaceAll('_',' ');
  evidence(state.demo?[['Road model','Synthetic'],['Positioning','Synthetic'],['Scale','Known example']]:[['Road model',row?.inference==='flow_tracked'?'Tracked from B2':'SegFormer B2'],['Positioning',state.job?.gps?'GPS track':'Visual depth / approximate'],['Assumed camera',state.job?.calibration?'Measured profile':`${state.job?.options?.assumed_height_m??1.5} m · ${state.job?.options?.diagonal_fov??90}° diagonal`]]);
  $('reviewNote').textContent=state.demo?'Explore the controls, then upload your own footage.':row?.reasons?.join(' · ')||'Awaiting road geometry.';
  drawBird();drawChart();drawMap();
}
function demoMap(){const route=[],footprints=[];for(let i=0;i<120;i++){const y=i*1.6,x=10*Math.sin(i/35);route.push({x,y,timestamp_s:i*.5,width_m:demoRow(i).width_m});if(i%3===0)footprints.push({points:[[x-3.6,y],[x+3.6,y],[x+3.9,y+6],[x-3.3,y+6]],rough:false});}return{route,footprints,context_points:[],bounds_m:[-14,-5,24,201],mode:'synthetic',route_length_m:194,extent_m:[38,206],unregistered_frames:0,disclaimer:'Synthetic map for demonstration only.'};}
let mapProjection=null;
function drawMap(){const[ctx,w,h]=setupCanvas(mapCanvas);ctx.fillStyle='#101914';ctx.fillRect(0,0,w,h);const data=state.demo?demoMap():state.map,strip=$('mapMode').value==='strip';
  if(strip){drawStrip(ctx,w,h);return;}
  if(!data){ctx.textAlign='center';ctx.fillStyle='#a3bba2';ctx.font='14px sans-serif';ctx.fillText(state.busy?'Building the full-survey map…':'The spatial map appears after processing',w/2,h/2);ctx.font='11px sans-serif';ctx.fillStyle='#728c72';ctx.fillText('The width strip can show all available timestamps now.',w/2,h/2+24);return;}
  const bounds=data.bounds_m,pad=55,spanX=Math.max(10,bounds[2]-bounds[0]),spanY=Math.max(10,bounds[3]-bounds[1]),base=Math.min((w-pad*2)/spanX,(h-pad*2)/spanY),scale=base*state.mapZoom,cx=(bounds[0]+bounds[2])/2,cy=(bounds[1]+bounds[3])/2;
  const project=p=>[w/2+(p[0]-cx)*scale+state.mapPan[0],h/2-(p[1]-cy)*scale+state.mapPan[1]];mapProjection={project,data};
  const rawStep=40/scale,power=10**Math.floor(Math.log10(Math.max(.01,rawStep))),step=[1,2,5,10].map(n=>n*power).find(n=>n>=rawStep)||power*10;
  ctx.font='9px monospace';ctx.fillStyle='#607762';ctx.lineWidth=.6;ctx.textAlign='center';
  const worldLeft=cx+(-w/2-state.mapPan[0])/scale,worldRight=cx+(w/2-state.mapPan[0])/scale,worldBottom=cy-(h/2-state.mapPan[1])/scale,worldTop=cy-(-h/2-state.mapPan[1])/scale;
  for(let x=Math.floor(worldLeft/step)*step;x<=worldRight;x+=step){const px=project([x,0])[0];path(ctx,[[px,25],[px,h-30]],null,'#25382a',.6);ctx.fillText(`${x.toFixed(step<1?1:0)}`,px,h-14);}
  ctx.textAlign='left';for(let y=Math.floor(worldBottom/step)*step;y<=worldTop;y+=step){const py=project([0,y])[1];path(ctx,[[35,py],[w-15,py]],null,'#25382a',.6);if(py>32&&py<h-32)ctx.fillText(y.toFixed(step<1?1:0),6,py+3);}
  ctx.save();ctx.beginPath();ctx.rect(35,25,w-50,h-55);ctx.clip();const palette={0:'#749d5555',1:'#a8b29d77',2:'#8094a577',3:'#8094a577',4:'#8094a577',8:'#4fa27566',9:'#72936366'};
  for(const p of data.context_points||[]){const q=project(p);ctx.fillStyle=palette[p[2]]||'#708d7788';ctx.fillRect(q[0],q[1],Math.max(1,scale*.55),Math.max(1,scale*.55));}
  for(const f of data.footprints||[]){path(ctx,f.points.map(project),f.lower_bound?'#d7ac4730':'#b5ed7520',f.rough?'#b5ed7533':'#b5ed7588',.7);}
  let segment=[];for(const p of data.route||[]){if(p.gap_before){path(ctx,segment,null,'#f0cc82',1.6);segment=[];}segment.push(project([p.x,p.y]));}path(ctx,segment,null,'#f0cc82',1.6);
  const route=data.route||[];if(route.length){const nearest=route.reduce((a,b)=>Math.abs(b.timestamp_s-state.time)<Math.abs(a.timestamp_s-state.time)?b:a);const p=project([nearest.x,nearest.y]);ctx.fillStyle=colors.lime;ctx.beginPath();ctx.arc(...p,5,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#111';ctx.lineWidth=2;ctx.stroke();const first=project([route[0].x,route[0].y]);ctx.fillStyle='#dddfcb';ctx.font='9px monospace';ctx.fillText('START',first[0]+8,first[1]+3);}
  ctx.restore();ctx.fillStyle='#c9dac2';ctx.textAlign='left';ctx.font='10px monospace';ctx.fillText(data.mode==='gps'?'NORTH ↑ / EAST → · m':data.mode==='synthetic'?'SYNTHETIC GEOMETRY · m':'APPROX. FORWARD ↑ / RIGHT → · m',12,16);ctx.textAlign='right';ctx.fillStyle='#91a987';ctx.fillText(`Observed extent ≈ ${data.extent_m[0]} × ${data.extent_m[1]} m`,w-12,h-14);
  const length=step*2,x=w-115,y=42;path(ctx,[[x,y],[x+length*scale,y]],null,colors.lime,2);ctx.fillStyle=colors.lime;ctx.font='9px monospace';ctx.textAlign='left';ctx.fillText(`${length.toFixed(length<1?1:0)} m`,x,y-8);
}
function drawStrip(ctx,w,h){mapProjection=null;const list=rows(),valid=list.filter(r=>widthOf(r)!=null),duration=clipDuration(),maxWidth=valid.length?Math.max(...valid.map(widthOf)):10,left=48,right=w-26,top=32,bottom=h-35,cx=(left+right)/2,scale=(right-left)/(Math.max(5,maxWidth)*1.4);
  ctx.fillStyle='#a6bca0';ctx.font='10px monospace';ctx.textAlign='left';ctx.fillText('FULL-VIDEO WIDTH STRIP · time ↑ is not distance · width → metres',12,17);ctx.font='9px monospace';
  for(let i=0;i<=6;i++){const y=top+i/6*(bottom-top);path(ctx,[[left,y],[right,y]],null,'#293c2c',.6);ctx.fillStyle='#708972';ctx.fillText(time(i/6*duration),6,y+3);}
  for(let i=-3;i<=3;i++){const x=cx+i*maxWidth/6*scale;path(ctx,[[x,top],[x,bottom]],null,'#293c2c',.6);ctx.textAlign='center';ctx.fillText(`${(i*maxWidth/6).toFixed(1)} m`,x,h-14);}
  for(let i=0;i<list.length;i++){const r=list[i],v=widthOf(r);if(v==null)continue;const y=top+r.timestamp_s/Math.max(.01,duration)*(bottom-top),next=list[i+1]?.timestamp_s??duration,th=Math.max(1,(next-r.timestamp_s)/Math.max(.01,duration)*(bottom-top));ctx.fillStyle=r.estimate_kind==='visible_lower_bound'?'#b9a65b70':'#a2d77965';ctx.fillRect(cx-v/2*scale,y,v*scale,th);}
  const y=top+state.time/Math.max(.01,duration)*(bottom-top);path(ctx,[[left,y],[right,y]],null,'#e0f7c7',1.2);ctx.textAlign='center';ctx.fillStyle='#d2e4c5';ctx.fillText('Centered for width comparison; this strip does not recover road turns.',w/2,h-2);
}
function refreshMapStats(){const data=state.demo?demoMap():state.map;$('mapSource').textContent=state.demo?'Synthetic':data?.mode==='gps'?'GPS aligned':data?'Visual depth · approx.':'Pending';$('mapLength').textContent=data?`${data.mode==='gps'?'':'≈ '}${data.route_length_m} m`:'—';$('mapExtent').textContent=data?`≈ ${data.extent_m.join(' × ')} m`:'—';$('mapCoverage').textContent=state.demo?'60 s · simulated':data?`${data.route.length} located · ${data.unregistered_frames} gaps`:'Processing';$('mapDisclaimer').textContent=state.demo?'Synthetic map for demonstration only.':data?.disclaimer||'A spatial map requires registered camera positions. The full-video width strip remains available when spatial tracking is incomplete.';$('mapSubtitle').textContent=state.demo?'An illustrative road corridor.':data?.mode==='gps'?'Local east/north positions from your GPS track; widths remain estimates.':'Depth-scaled visual motion plus projected context. Dimensions are approximate.';drawMap();}
function seek(t){state.time=Math.max(0,Math.min(clipDuration(),t));state.index=state.demo?Math.min(119,Math.floor(state.time*2)):indexAt(state.time);if(videoMode()&&Number.isFinite(video.duration))video.currentTime=Math.min(state.time,video.duration);refresh();}
function selectJob(id){clearTimeout(state.poll);video.pause();state.demo=false;state.playing=false;state.index=0;state.time=0;state.results=[];state.job={id};state.map=null;state.mapKey=null;state.videoKey=null;state.imageKey=null;state.image=null;state.mapZoom=1;state.mapPan=[0,0];remembered(id);history.replaceState(null,'',`?survey=${id}`);setBusy(true);$('progressWrap').hidden=false;$('viewMode').value='video';loadVideo();refresh();refreshMapStats();pollJob(id);}
async function pollJob(id){try{const response=await fetch(`/api/jobs/${id}?after=${state.results.length}`);if(response.status===404){setBusy(false);remembered(null);$('statusTitle').textContent='Saved survey not found. Start a new survey.';return;}if(!response.ok)throw Error('Cannot read survey status');const job=await response.json();if(state.job?.id!==id)return;state.results=job.result_start===0?job.results:[...state.results,...job.results];state.job={...job,results:undefined};$('surveyName').textContent=job.filename;$('surveySubtitle').textContent=job.version==='0.2'?'FULL VIDEO · SEGFORMER B2 + DEPTH V2':'LEGACY ANALYSIS · RE-ANALYZE TO UPGRADE';$('modeBadge').textContent=job.calibration?'CALIBRATED + ROUGH DEPTH':job.version==='0.2'?'ROUGH METRES / ASSUMPTIONS SHOWN':'LEGACY / UNSCALED';$('statusTitle').textContent=job.message||job.status;$('statusDetail').textContent=`${job.processed_video_frames||0}/${job.video_frames||'?'} video frames · ${state.results.length} snapshots · ${job.semantic_frames||0} model frames`;$('progressBar').style.width=`${Math.round((job.progress||0)*100)}%`;$('sourceNotice').hidden=!(job.source_notice||job.version!=='0.2');$('sourceNotice').textContent=job.source_notice||(job.version!=='0.2'?'This older survey saved only sampled images. Re-analyze to get rough widths from those images, or re-upload the original for full-motion masked video.':'');
  if(job.map_url&&state.mapKey!==job.map_url){const mapResponse=await fetch(job.map_url);if(mapResponse.ok){state.map=await mapResponse.json();state.mapKey=job.map_url;refreshMapStats();}}
  const complete=['complete','failed','cancelled','interrupted'].includes(job.status);setBusy(!complete);$('reprocessButton').hidden=!complete;$('videoExport').disabled=!job.annotated_url;$('mapExport').disabled=!job.map_url;loadVideo();refresh();if(complete){if(job.status==='failed')$('reviewNote').textContent='Analysis failed: '+job.message;return;}state.poll=setTimeout(()=>pollJob(id),1800);
  }catch(error){$('statusTitle').textContent=`Connection interrupted: ${error.message}`;$('statusDetail').textContent='Retrying in 5 seconds';state.poll=setTimeout(()=>pollJob(id),5000);}}
function resetDemo(){if(state.busy)return;clearTimeout(state.poll);video.pause();state.demo=true;state.playing=true;state.index=0;state.time=0;state.job=null;state.results=[];state.map=null;state.mapKey=null;state.videoKey=null;state.mapZoom=1;state.mapPan=[0,0];remembered(null);history.replaceState(null,'',location.pathname);$('surveyName').textContent='The coastal approach';$('surveySubtitle').textContent='INTERACTIVE SYNTHETIC DEMO';$('modeBadge').textContent='DEMO / ILLUSTRATIVE';$('sourceNotice').hidden=true;$('reprocessButton').hidden=true;$('progressWrap').hidden=true;$('statusTitle').textContent='Bring your own road.';$('statusDetail').textContent='Full-length video · optional GPS · rough metre estimates';loadVideo();refresh();refreshMapStats();}
document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('uploadButton').onclick=()=>$('uploadDialog').showModal();$('infoButton').onclick=$('infoNav').onclick=()=>$('infoDialog').showModal();$('mapNav').onclick=()=>$('mapPanel').scrollIntoView({behavior:'smooth'});$('sceneNav').onclick=()=>$('scene').scrollIntoView({behavior:'smooth'});$('demoButton').onclick=resetDemo;
$('videoInput').onchange=()=>{$('fileLabel').textContent=$('videoInput').files[0]?.name||'Choose a dashcam video';$('uploadError').textContent='';};
$('uploadForm').onsubmit=async event=>{event.preventDefault();if(state.busy)return;const file=$('videoInput').files[0];if(!file)return;const error=$('uploadError');error.textContent='';if(file.size>500*1024*1024){error.textContent='Clip exceeds 500 MB';return;}const calibration=$('calibrationInput').value.trim();if(calibration){try{JSON.parse(calibration);}catch{error.textContent='Camera calibration must be valid JSON';return;}}
  const form=new FormData();form.append('video',file);form.append('calibration',calibration);for(const[name,id]of[['sample_hz','sampleRate'],['keyframe_hz','keyframeRate'],['estimate_mode','estimateMode'],['diagonal_fov','fovInput'],['assumed_height_m','heightInput'],['hood_percent','hoodInput'],['gps_offset_s','gpsOffset']])form.append(name,$(id).value);const gps=$('gpsInput').files[0];if(gps)form.append('gps',gps);setBusy(true);$('analyzeButton').textContent='Uploading…';
  try{const response=await fetch('/api/jobs',{method:'POST',body:form}),data=await response.json();if(!response.ok)throw Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));$('uploadDialog').close();selectJob(data.id);}catch(e){error.textContent=e.message;setBusy(false);}finally{$('analyzeButton').innerHTML='Analyze full video <span>↗</span>';}};
$('reprocessButton').onclick=async()=>{if(state.busy||!state.job)return;setBusy(true);try{const response=await fetch(`/api/jobs/${state.job.id}/reprocess`,{method:'POST'}),data=await response.json();if(!response.ok)throw Error(data.detail);selectJob(data.id);}catch(e){setBusy(false);$('statusTitle').textContent=e.message;}};
$('cancelButton').onclick=async()=>{if(!state.job)return;try{await fetch(`/api/jobs/${state.job.id}/cancel`,{method:'POST'});$('statusTitle').textContent='Stopping after the current conversion or inference operation…';}catch(e){$('statusTitle').textContent=e.message;}};
$('playButton').onclick=()=>{if(videoMode()){if(video.paused)video.play().catch(()=>{});else video.pause();}else{state.playing=!state.playing;refresh();}};
video.onplay=()=>{state.playing=true;$('playButton').textContent='Ⅱ';};video.onpause=()=>{state.playing=false;$('playButton').textContent='▶';};video.onended=()=>{state.playing=false;refresh();};video.onerror=()=>{$('viewerCaption').textContent='Video playback failed. Try the annotated MP4 download or Inspect frames.';};
$('timeline').oninput=event=>{state.playing=false;video.pause();seek(Number(event.target.value));};$('playbackSpeed').onchange=()=>video.playbackRate=Number($('playbackSpeed').value);
$('viewMode').onchange=()=>{const playing=state.playing;loadVideo();state.playing=playing;refresh();};$('overlayToggle').onchange=()=>{const playing=state.playing;loadVideo();state.playing=playing;refresh();};$('lineToggle').onchange=refresh;
chart.onclick=event=>{const r=chart.getBoundingClientRect();state.playing=false;video.pause();seek(Math.max(0,Math.min(1,(event.clientX-r.left-34)/(r.width-42)))*clipDuration());};
$('fullscreenButton').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('scene').requestFullscreen();}catch{$('statusTitle').textContent='Fullscreen unavailable';}};
$('mapMode').onchange=()=>{state.mapZoom=1;state.mapPan=[0,0];drawMap();};$('mapFit').onclick=()=>{state.mapZoom=1;state.mapPan=[0,0];drawMap();};$('zoomIn').onclick=()=>{state.mapZoom=Math.min(12,state.mapZoom*1.3);drawMap();};$('zoomOut').onclick=()=>{state.mapZoom=Math.max(.3,state.mapZoom/1.3);drawMap();};
mapCanvas.onwheel=event=>{if($('mapMode').value==='strip')return;event.preventDefault();state.mapZoom=Math.max(.3,Math.min(12,state.mapZoom*(event.deltaY<0?1.15:1/1.15)));drawMap();};let drag=null;
mapCanvas.onpointerdown=event=>{drag={x:event.clientX,y:event.clientY,pan:[...state.mapPan],moved:false};mapCanvas.setPointerCapture(event.pointerId);};mapCanvas.onpointermove=event=>{if(!drag||$('mapMode').value==='strip')return;const dx=event.clientX-drag.x,dy=event.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>4)drag.moved=true;state.mapPan=[drag.pan[0]+dx,drag.pan[1]+dy];drawMap();};mapCanvas.onpointerup=event=>{if(!drag)return;if(!drag.moved){const rect=mapCanvas.getBoundingClientRect(),x=event.clientX-rect.left,y=event.clientY-rect.top;if($('mapMode').value==='strip'){state.playing=false;video.pause();seek(Math.max(0,Math.min(1,(y-32)/(rect.height-67)))*clipDuration());}else if(mapProjection?.data?.route?.length){const nearest=mapProjection.data.route.map(p=>({p,xy:mapProjection.project([p.x,p.y])})).sort((a,b)=>Math.hypot(a.xy[0]-x,a.xy[1]-y)-Math.hypot(b.xy[0]-x,b.xy[1]-y))[0];if(Math.hypot(nearest.xy[0]-x,nearest.xy[1]-y)<35){state.playing=false;video.pause();seek(nearest.p.timestamp_s);}}}drag=null;};
function saveBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('mapDownload').onclick=()=>mapCanvas.toBlob(blob=>{if(blob)saveBlob(blob,state.demo?'synthetic-road-map.png':'road-survey-map.png');});
$('exportButton').onclick=()=>{$('exportNote').textContent=state.demo?'Synthetic demonstration export—not a real survey.':'Rough estimates, calibration and positioning provenance remain labeled in all exports.';$('videoExport').disabled=state.demo||!state.job?.annotated_url;$('mapExport').disabled=state.demo||!state.job?.map_url;$('exportDialog').showModal();};
function exportData(format){if(state.demo){saveBlob(new Blob([format==='csv'?'source,timestamp_s,illustrative_width_m\n'+rows().map(r=>`synthetic,${r.timestamp_s},${r.width_m}`).join('\n'):JSON.stringify({synthetic:true,results:rows()},null,2)],{type:format==='csv'?'text/csv':'application/json'}),`synthetic-demo.${format}`);return;}if(!state.job)return;const a=document.createElement('a');a.href=`/api/jobs/${state.job.id}/export?format=${format}`;a.download='';a.click();}
$('jsonExport').onclick=()=>exportData('json');$('csvExport').onclick=()=>exportData('csv');$('videoExport').onclick=()=>{if(!state.job?.annotated_url)return;const a=document.createElement('a');a.href=state.job.annotated_url+'&download=true';a.download='';a.click();};$('mapExport').onclick=()=>{if(state.map)saveBlob(new Blob([JSON.stringify(state.map,null,2)],{type:'application/json'}),'road-survey-map.json');};
let lastAnimation=0,lastRefresh=0;function animate(now){const delta=Math.min(.1,(now-lastAnimation)/1000||0);lastAnimation=now;if(videoMode()){state.time=video.currentTime||0;const index=indexAt(state.time);if(index!==state.index||now-lastRefresh>200){state.index=index;refresh();lastRefresh=now;}}else{if(state.playing){state.time+=delta*Number($('playbackSpeed').value);if(state.time>=clipDuration()){state.time=0;if(!state.demo)state.playing=false;}const index=state.demo?Math.min(119,Math.floor(state.time*2)):indexAt(state.time);if(index!==state.index||now-lastRefresh>250){state.index=index;refresh();lastRefresh=now;}}const[ctx,w,h]=setupCanvas(scene);if(state.demo)drawDemo(ctx,w,h,state.time);else drawReal(ctx,w,h,current());}requestAnimationFrame(animate);}
new ResizeObserver(()=>{drawBird();drawChart();drawMap();}).observe(document.querySelector('.workspace'));
fetch('/api/health').then(r=>r.json()).then(j=>{$('connection').textContent=`Local engine · ${j.version||'0.1'}`;}).catch(()=>{$('connection').textContent='Engine offline';});
let saved=new URLSearchParams(location.search).get('survey');try{saved=saved||localStorage.getItem('rtr-job');}catch{}if(saved&&/^[a-f0-9]{32}$/.test(saved))selectJob(saved);else resetDemo();requestAnimationFrame(animate);
